server {
    listen 80;
    server_name localhost;

    # La ruta donde Docker pondrá los archivos de Angular
    root /usr/share/nginx/html;
    index index.html;

    # Regla de oro para Angular: Si no encuentras el archivo, carga el index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optimización Premium RMS: Guardar en caché imágenes, íconos y estilos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
